/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supervisedandunsupervised;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;

/**
 *
 * @author Elcot
 */
public class FindEmotions extends javax.swing.JFrame {

    /**
     * Creates new form FindEmotions
     */
    
    public static ArrayList allOpinions=new ArrayList();
    
    public FindEmotions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel1.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Find Emotions of Each Reviews");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jButton1.setText("Find Emotions of each reviews based on Helpfulness Protocol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Comparison between each Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            /* Helpfulness Protocol */
        
        ArrayList Trust=new ArrayList();
        ArrayList Anticipation=new ArrayList();
        ArrayList Joy=new ArrayList();
        ArrayList Surprise=new ArrayList();
        ArrayList Anxiety=new ArrayList();
        ArrayList Anger=new ArrayList();
        ArrayList Sadness=new ArrayList();
        ArrayList Disgust=new ArrayList();        
        
        try
        {
            File fe2=new File("NRC-Emotion-Lexicon-Wordlevel-v0.92.txt");
            FileInputStream fis2=new FileInputStream(fe2);
            byte data2[]=new byte[fis2.available()];
            fis2.read(data2);
            fis2.close();
                
            String sg2[]=new String(data2).trim().split("\n");
               
            for(int i=0;i<sg2.length;i++)
            {
                if(sg2[i].trim().contains("\t"))
                {
                    String sp[]=sg2[i].trim().split("\t");
                    if(sp[1].trim().equals("trust"))
                    {
                        Trust.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("anticipation"))
                    {
                        Anticipation.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("joy"))
                    {
                        Joy.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("surprise"))
                    {
                        Surprise.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("anxiety"))
                    {
                        Anxiety.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("anger"))
                    {
                        Anger.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("sadness"))
                    {
                        Sadness.add(sp[0].trim());
                    }
                    if(sp[1].trim().equals("disgust"))
                    {
                        Disgust.add(sp[0].trim());
                    }
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
        ArrayList allReviews=MainFrame.allReviews;
        
        jTextArea1.setText("");
        for(int k=0;k<allReviews.size();k++)
        {
            String rev=allReviews.get(k).toString().trim().replaceAll("[^\\w\\s]", "");     // replace all symbols
            String g2[]=rev.trim().split(" ");
            int trust=0,anticipation=0,joy=0,surprise=0,anxiety=0,anger=0,sadness=0,disgust=0;
            for(int j=0;j<g2.length;j++)
            {
                String g3=g2[j].trim();
                if(Trust.contains(g3.trim()))
                {
                    trust++;
                }
                if(Anticipation.contains(g3.trim()))
                {
                    anticipation++;
                }
                if(Joy.contains(g3.trim()))
                {
                    joy++;
                }
                if(Surprise.contains(g3.trim()))
                {
                    surprise++;
                }
                if(Anxiety.contains(g3.trim()))
                {
                    anxiety++;
                }
                if(Anger.contains(g3.trim()))
                {
                    anger++;
                }
                if(Sadness.contains(g3.trim()))
                {
                    sadness++;
                }
                if(Disgust.contains(g3.trim()))
                {
                    disgust++;
                }
            }
            
            int arr[]={trust,anticipation,joy,surprise,anxiety,anger,sadness,disgust};
            int maxValue=getMaxValue(arr);
            
            String res="Trust";
            if(maxValue == anticipation)
            {
                res="Anticipation";                
            }
            if(maxValue == joy)
            {
                res="Joy";                
            }
            if(maxValue == surprise)
            {
                res="Surprise";                
            }
            if(maxValue == anxiety)
            {
                res="Anxiety";                
            }
            if(maxValue == anger)
            {
                res="Anger";                
            }
            if(maxValue == sadness)
            {
                res="Sadness";                
            }
            if(maxValue == disgust)
            {
                res="Disgust";                
            }
            jTextArea1.append(rev.trim()+" --> "+res.trim()+"\n\n");
            allOpinions.add(res.trim());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ProductComparison pc=new ProductComparison();
        pc.setTitle("Product Comparison");
        pc.setVisible(true);
        pc.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindEmotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindEmotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindEmotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindEmotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindEmotions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public static int getMaxValue(int[] numbers)
    {
        int maxValue = numbers[0];
        for(int i=1;i < numbers.length;i++){
          if(numbers[i] > maxValue){
                maxValue = numbers[i];
              }
        }
        return maxValue;
    }
}
